init:
    - git config --global core.autocrlf true

os:
  - Visual Studio 2015

platform:
    - x64
    - x86

build:
  verbosity: detailed

install:
    ############################################################################
    #                                  Ninja                                   #
    ############################################################################
    - set NINJA_URL="https://github.com/ninja-build/ninja/releases/download/v1.7.2/ninja-win.zip"
    - appveyor DownloadFile %NINJA_URL% -FileName ninja.zip
    - 7z x ninja.zip -oC:\projects\dev\ninja > nul
    - set PATH=%PATH%;C:\projects\dev\ninja
    - ninja --version
    ############################################################################
    #                            LLVM: llvm-config                             #
    ############################################################################
    - ls C:\Libraries\llvm-4.0.0\bin
    - set PATH=%PATH%;C:\Libraries\llvm-4.0.0\bin
    ############################################################################
    #                             LLVM: clang-cl                               #
    ############################################################################
    - set PATH=%PATH%;"C:\Program Files\LLVM\bin"
    - clang-cl -v
    - set CC=clang-cl
    - set CXX=clang-cl
    - call "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat" x86_amd64


build_script:
    - mkdir build
    - cd build
    - cmake -G Ninja -DCMAKE_BUILD_TYPE=Release -DCMAKE_CXX_COMPILER=clang-cl ..
    - cmake --build .

artifacts:
    - path: 'vsl-bindgen*'
      name: VSL Bindgen
      type: File
